### PR TITLE
added contrutors.html - Abhishek

### PR DESCRIPTION
**Pull request by its-abhishek**
#54 review @SarthakSKumar

### CODE REVIEW

**Review by SarthakSKumar — CHANGES_REQUESTED** [review]
Please give an appropriate PR Title.

**Comment by its-abhishek** [comment]
#58 added contribution.html file to the website

**Review by SarthakSKumar — CHANGES_REQUESTED** [review]
Add appropriate PR Title

**Comment by its-abhishek** [comment]
#58 Added contributos image to the website

**Review by SarthakSKumar — CHANGES_REQUESTED** [review]
Please give an appropriate PR Title.  (PS: Spelling)

**Comment by its-abhishek** [comment]
#58 added Contributor Profile Images to the website

**Review by SarthakSKumar — CHANGES_REQUESTED** [review]
Please check the PR Title

**Comment by SarthakSKumar** [comment]
Issue no longer valid as website has been moved to a vite app. @its-abhishek

**Pull request closed without merging**
