### PR TITLE
Created a static website showing the list of projects in this repo. With a link to the respective folders

### PR DESCRIPTION
**Pull request by its-abhishek**
Hi I'm Abhishek,
PES University.
PR : #11

### CODE REVIEW

**Review by SarthakSKumar — CHANGES_REQUESTED** [review]
Great work. A few changes. Change the website name to the current repository name. Rename the website folder to just 'Website'. Also,, attach a screenshot of the website here @its-abhishek

**Comment by its-abhishek** [comment]
As per the request changes done
PR: #13 
iot project4
iot project13

**Review by SarthakSKumar — CHANGES_REQUESTED** [review]
Forgot to mention. Place the website folder in the root of the repository. Not inside the arduino projects folder. @its-abhishek

**Review by SarthakSKumar — APPROVED** [review]
Good Work @its-abhishek

**Pull request merged**
