### PR TITLE
Light Sensing System

### PR DESCRIPTION
**Pull request by Sohoxic**
I'm Soham Sarkar of PES University, I've worked in fixing issue no #19 .

### CODE REVIEW

**Review by SarthakSKumar — CHANGES_REQUESTED** [review]
Can you remove the brandings from the circuit diagrams and block diagrams you have attached please?

**Comment by Sohoxic** [comment]
yesss will surely do that.

**Comment by Sohoxic** [comment]
@SarthakSKumar I've removed the branding from the circuit diagrams and block diagrams.

**Review by SarthakSKumar — APPROVED** [review]
Good Work @Sohoxic

**Pull request merged**
